version: '3.9'

services:
  java_db:
    container_name: java_db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}